### ISSUE TITLE
Beta updates merged!

### ISSUE THREAD

**Issue by quiddity-wp** [ipeterov/noita-progress#1]
Hi, Thanks for this tool! :)
I was wondering if you could update it, now that all the beta content has been merged into the Main branch?
Or if I should try to nerd-snipe another volunteer-dev in the discord to have a go?
Cheers!

**Comment by ipeterov** [comment]
Hey, thanks for the reminder 👍 

#2 is now merged & deployed, so the site should be up-to-date ✔️
